### ISSUE TITLE
RasterInterfaceCapabilities error

### ISSUE THREAD

**Issue by JSS2000** [gee-community/qgis-earthengine-plugin#151] opened 2024-08-12 17:33 UTC
Hi,
I am tring to fix that error:
TypeError: invalid result from EarthEngineRasterDataProvider.capabilities(), RasterProviderCapabilities cannot be converted to qgis._core.RasterInterfaceCapabilities in this context

My QGIS version is : 3.38  and GEE plugin is 0.6.

Someone has some clue?

**Comment by JSS2000** [comment] 2024-08-13 09:13
Hi, XavierCLL,
that is the code
`# Centraliza o mapa
Map.setCenter(-8.014008631440426, 38.5333478267441, 20)
# Carregar a coleção de imagens Sentinel-2 e filtrar pela área de interesse
image = ee.ImageCollection("COPERNICUS/S2").filterBounds(center).first(); # Selecionar a primeira imagem da coleção

# Defina o caminho do asset do seu polígono no GEE
tailao_asset = 'projects/ee-ndvieto/assets/mitra1'  # Substitua pelo seu caminho de asset do GEE
# Carregar a coleção de polígonos como um FeatureCollection
tailao = ee.FeatureCollection(tailao_asset)
# Faça o clip da imagem com o polígono
imagem_clipada = image.clipToCollection(tailao)
# Calcular o NDVI
ndvi = imagem_clipada.normalizedDifference(['B8', 'B4']).rename('NDVI')

# Adicionar a camada NDVI ao mapa
Map.addLayer(ndvi, {min: -1, max: 1, palette: ['blue', 'white', 'green']}, 'NDVI')

# Exportar o NDVI para o Google Drive (ou outro serviço) se desejar, caso precise baixar
Export.image.toDrive({
  image: ndvi,
  description: 'NDVI_Clipado',
  scale: 10,
  region: tailao
})
`
``

**Comment by JSS2000** [comment] 2024-08-13 09:14
Hi, @XavierCLL . That is the code:
# Centraliza o mapa
Map.setCenter(-8.014008631440426, 38.5333478267441, 20)
# Carregar a coleção de imagens Sentinel-2 e filtrar pela área de interesse
image = ee.ImageCollection("COPERNICUS/S2").filterBounds(center).first(); # Selecionar a primeira imagem da coleção

# Defina o caminho do asset do seu polígono no GEE
tailao_asset = 'projects/ee-ndvieto/assets/mitra1'  # Substitua pelo seu caminho de asset do GEE
# Carregar a coleção de polígonos como um FeatureCollection
tailao = ee.FeatureCollection(tailao_asset)
# Faça o clip da imagem com o polígono
imagem_clipada = image.clipToCollection(tailao)
# Calcular o NDVI
ndvi = imagem_clipada.normalizedDifference(['B8', 'B4']).rename('NDVI')

# Adicionar a camada NDVI ao mapa
Map.addLayer(ndvi, {min: -1, max: 1, palette: ['blue', 'white', 'green']}, 'NDVI')

# Exportar o NDVI para o Google Drive (ou outro serviço) se desejar, caso precise baixar
Export.image.toDrive({
  image: ndvi,
  description: 'NDVI_Clipado',
  scale: 10,
  region: tailao
})

**Comment by JSS2000** [comment] 2024-08-13 09:18
other code:


Map.setCenter(-8.014008631440426, 38.5333478267441, 20)
image = ee.ImageCollection("COPERNICUS/S2").filterBounds(Map.getCenter()).first()
Map.addLayer(image, {'bands': 'B4,B3,B2', 'min': 0, 'max': 5000, 'gamma': 1.4}, 'RGBTrueColor')
tailao_asset = 'projects/ee-ndvieto/assets/mitra1'  # Substitua pelo seu caminho de asset do GEE
tailao = ee.FeatureCollection(tailao_asset)
imagem_clipada = image.clipToCollection(tailao)
Map.addLayer(imagem_clipada, {'bands': 'B4,B3,B2', 'min': 0, 'max': 5000, 'gamma': 1.4}, 'Imagem Clipada Tailao')

**Comment by XavierCLL** [comment] 2024-08-14 03:53
I couldn't test completely because 'projects/ee-ndvieto/assets/mitra1' does not exist, but this code that is part of your code works for me:

```
import ee
from ee_plugin import Map
ee.Initialize()
Map.setCenter(-8.014008631440426, 38.5333478267441, 20)
image = ee.ImageCollection("COPERNICUS/S2").filterBounds(Map.getCenter()).first()
ndvi = image.normalizedDifference(['B8', 'B4']).rename('NDVI')
Map.addLayer(ndvi, {'min': -1, 'max': 1, 'palette': ['blue', 'white', 'green']}, 'NDVI')
```
most likely you have an issue with your code

**Comment by JSS2000** [comment] 2024-08-14 13:21
I run the code like yours and return same error with added lines:
TypeError: EarthEngineRasterDataProvider.readNativeAttributeTable() missing 1 required positional argument: 'errorMessage'

Maybe is some python library in fault.

**Comment by XavierCLL** [comment] 2024-08-14 17:42
That was fixed in https://github.com/gee-community/qgis-earthengine-plugin/pull/140 but has not been released yet, but for now you can use this https://github.com/gee-community/qgis-earthengine-plugin/issues/133#issuecomment-2248775157 zip with the fixes

**Comment by JSS2000** [comment] 2024-08-16 11:38
Thank you, @XavierCLL . Indeed, it has been corrected. However, that error , continue :  TypeError: invalid result from EarthEngineRasterDataProvider.capabilities(), RasterProviderCapabilities cannot be converted to qgis._core.RasterInterfaceCapabilities in this context . What is the QGIS version that you have used to run that code?

**Comment by XavierCLL** [comment] 2024-08-16 18:38
@JSS2000 error confirmed, I usually use a lts version but with the latest version of Qgis 3.38 capabilities() need to be updated, I'm going to fix it, thanks!

**Comment by XavierCLL** [comment] 2024-08-16 21:06
fixed, test with this:
[ee_plugin.zip](https://github.com/user-attachments/files/16641723/ee_plugin.zip)

**Comment by JSS2000** [comment] 2024-08-19 08:33
Thank you, @XavierCLL with that upgrade , works!

**Closed** 2024-08-19 17:45 UTC
