### ISSUE TITLE
Failure to install on QGIS 3.10 Windows

### ISSUE THREAD

**Issue by Timo65** [gee-community/qgis-earthengine-plugin#50] opened 2020-03-04 09:38 UTC
Couldn't load plugin 'ee_plugin' due to an error when calling its classFactory() method 

Exception: Problem requesting tokens. Please try again.  HTTP Error 400: Bad Request b'{\n  "error": "invalid_grant",\n  "error_description": "Bad Request"\n}' 
Traceback (most recent call last):
  File "C:/Users/Timothy.Macqueen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\ee_auth.py", line 19, in init
    ee.Initialize()
  File "C:\Users\Timothy.Macqueen\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\__init__.py", line 123, in Initialize
    ApiFunction.initialize()
  File "C:\Users\Timothy.Macqueen\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\apifunction.py", line 154, in initialize
    signatures = data.getAlgorithms()
  File "C:\Users\Timothy.Macqueen\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\data.py", line 952, in getAlgorithms
    return send_('/algorithms', {}, 'GET')
  File "C:\Users\Timothy.Macqueen\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\data.py", line 1797, in send_
    'Server returned HTTP code: %d' % response.status)
ee.ee_exception.EEException: Server returned HTTP code: 404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Timothy.Macqueen\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\oauth.py", line 79, in request_token
    parse.urlencode(request_args).encode()).read().decode()
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/Timothy.Macqueen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 25, in classFactory
    from .ee_plugin import GoogleEarthEnginePlugin
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Timothy.Macqueen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\ee_plugin.py", line 26, in 
    ee_plugin.ee_auth.init()
  File "C:/Users/Timothy.Macqueen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\ee_auth.py", line 21, in init
    authenticate()
  File "C:/Users/Timothy.Macqueen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\ee_auth.py", line 48, in authenticate
    ee.oauth._obtain_and_write_token(token.strip())
  File "C:\Users\Timothy.Macqueen\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\oauth.py", line 128, in _obtain_and_write_token
    token = request_token(auth_code)
  File "C:\Users\Timothy.Macqueen\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\oauth.py", line 83, in request_token
    (e, e.read()))
Exception: Problem requesting tokens. Please try again.  HTTP Error 400: Bad Request b'{\n  "error": "invalid_grant",\n  "error_description": "Bad Request"\n}'

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.10.2-A Coruña A Coruña, d4cd3cfe5a 

Python Path:
C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python
C:/Users/Timothy.Macqueen/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Timothy.Macqueen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS3~1.10\apps\Python37
C:\PROGRA~1\QGIS3~1.10\apps\Python37\Scripts
C:\Program Files\QGIS 3.10\bin\python37.zip
C:\PROGRA~1\QGIS3~1.10\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib
C:\Program Files\QGIS 3.10\bin
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\Pythonwin
C:/Users/Timothy.Macqueen/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\Timothy.Macqueen\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
D:/2019-2020/Projects/Kartoza GIS training
C:\Users\Timothy.Macqueen\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows

**Comment by gena** [comment] 2020-03-20 16:08
I hope it's a duplicate of #51

**Closed by gena** 2020-03-20 16:08 UTC
